### PR TITLE
[JOLINT-57] form state

### PR DESCRIPTION
**Pull request by ell-ska**
1. prepared all the different parts of the form
2. added Jolints text for the different chapters
3. created a hook that uses [zustand](https://github.com/pmndrs/zustand) for state management
4. prepared the form for navigation

### CODE REVIEW

**Review by idamakela — APPROVED** [review]
I REALLY like this implementation, that zustand package seems very useful. NGL, took some time to fully get the code. Maybe worth sharing with the others because of the complexity of it and to learn from each other.

**Comment by ell-ska** [comment]
ready for testing on development:
not really sure how to test it tho since nothing is visible, make sure the site not crashed

**Comment by idamakela** [comment]
DEV TEST: APPROVES, but seems to have a weird responsive layout which is probably another ticket bug

**Comment by ell-ska** [comment]
oops, i accidentally merged in the unresponsive code, should be fixed now!

**Comment by idamakela** [comment]
DEV TEST: APPROVED!
It's responsive and did not crash the site hih

**Pull request merged**
