### PR TITLE
[FIX-51] consent input signature

### PR DESCRIPTION
**Pull request by idamakela**
- removed signature input field
- added radix checkbox
- updated userInput object

### CODE REVIEW

**Review by DavidDyberg — APPROVED** [review]
Code looks great!

**Review by petksks — APPROVED** [review]
useState Type Annotation: its good to see that useState is typed with UserInputType. This helps with type safety, well done!

State Update for Checkbox: Youre replacing the entire userInput state when the checkbox changes. This is unnecessary as you could use a functional update to ensure that the rest of the userInput state is preserved. But that is more of a preference thing.

All in all I think it looks good.

**Comment by idamakela** [comment]
Updated the code in accordance to Peters suggestion!

**Comment by idamakela** [comment]
### Ready for dev test!

**Comment by petksks** [comment]
I have tested it in the develop and it is probably one of the best signature functions I have ever seen. 🥺🥺

**Pull request merged**
