### PR TITLE
[HOTFIX] reset main and re-merge features and fixes

### PR DESCRIPTION
**Pull request by idamakela**
## Main was tainted with a bad feature (fix/j25) and required a hotfix, what I have done is:

1. Created hotfix-test branch from main
2. Identified where the bad merge was introduced 
3. On hotfix-test branch: git reset --hard 0fb88cd7b49
4. Identified features and fixes that need to be re-introduced in the codebase
5. Get affected remote branches local 
6. Merge in feature/j57
7. Merge in feature/j72
8. Merge in feature/j81
9. Merge in fix/j41-change-padding...
10. Merge in fix/j42-responsive-footer
11. Created a pull request to main

## Other affected branches that need to re-merge the correct version of main are:
- feature/j68
- fix/j25
- feature/j78
- fix/j42-footer-fix-responsive

## Commit hash id that introduced the issue: 8473211da5d8ae993bf8196de3d580b68ff75f1b
- Meaning if you have this commit as a parent in the branch you are working on, you need to re-merge main after it has been fixed

### **THIS PULL REQUEST REQUIRES ALL AFFECTED CODE CONTRIBUTORS TO LOOK OVER THE CODE AND REVIEW THAT THE CORRECT VERSION HAS BEEN RE-INTRODUCED!**

❗❗❗ This review needs to be made by getting the remote branch to your local machine since it does not show all of the files added here in the github pull request, only resolved merge  conflicts it seems like ❗❗❗

### CODE REVIEW

**Comment by idamakela** [comment]
❗❗❗ This review needs to be made by getting the remote branch to your local machine since it does not show all of the files add here in the github pull request

**Comment by idamakela** [comment]
I have now also changed the z-index for the info-page header.
Note that main and landing page for the info-page has weird styling, and therefore need to be overlooked.

**Comment by ell-ska** [comment]
aaah now i see. david and i had both been doing changes in the header file and had some conflicts to resolve there, it looks like you didn't handle the conflict correctly and that's why it looks weird, [here](https://github.com/ell-ska/jolint/blob/8db824d255048329636b0093903010ad869e7be0/app/(info-page)/_components/Header.tsx) is the correct header file

also in Hero.tsx on line 9 there is a px-6 that should be removed

and i don't really think we've been styling all the way down to 320px hahah, it looks fine until about 350px but that small phones aren't very common. the smallest iphone is 375px. im guessing most androids aren't smaller that that either

**Comment by idamakela** [comment]
## Two new commits 
* Changed info page header to correct code, copy pasted from Ella's link above
* Removed px-8 from info page hero component

**Review by ell-ska — APPROVED** [review]
everything looks good to me now!

**Comment by idamakela** [comment]
### OK from group to merge hotfix-test to main in teams channel

**Comment by idamakela** [comment]
## How I merged hotfix to main

1. Tried git merge on local machine - did not work - aborted, but got error message (fatal: There is no merge to abort (MERGE_HEAD missing))
2. Tried: git revert 0fb88cd7b498e51ad2605e3261ab6b4e5360c1a0 - got conflict in sidebar - git revert --abort
3. Forgot that I did a reset, not a revert.
4. git reset 0fb88cd7b498e51ad2605e3261ab6b4e5360c1a0 
5. committed the reset
6. git merge hotfix-test 
7. opened localhost and checked the frontend styling on infopage header and FAQ and dashboard footer - looks good 
8. checked the codebase - Ellas code is in there (feature/j57)
9. git push - got error 
      (To github.com:ell-ska/jolint.git
       ! [rejected]        main -> main (non-fast-forward)
      error: failed to push some refs to 'github.com:ell-ska/jolint.git'
      hint: Updates were rejected because the tip of your current branch is behind
      hint: its remote counterpart. If you want to integrate the remote changes,
      hint: use 'git pull' before pushing again.
      hint: See the 'Note about fast-forwards' in 'git push --help' for details.)
10. conclusion from above error: remote needs to be reset or overwrite it with the local changes
11. git push --force-with-lease - got error 
      (Enumerating objects: 28, done.
      Counting objects: 100% (25/25), done.
      Delta compression using up to 8 threads
      Compressing objects: 100% (12/12), done.
      Writing objects: 100% (12/12), 1.22 KiB | 1.22 MiB/s, done.
      Total 12 (delta 7), reused 0 (delta 0), pack-reused 0
      remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
      remote: error: GH006: Protected branch update failed for refs/heads/main.
      remote: error: Changes must be made through a pull request. Cannot force-push to this branch
      To github.com:ell-ska/jolint.git
      ! [remote rejected] main -> main (protected branch hook declined)
      error: failed to push some refs to 'github.com:ell-ska/jolint.git')
12. ...

**Pull request merged**
