### PR TITLE
[JOLINT-29] dropdown component

### PR DESCRIPTION
**Pull request by ell-ska**

### CODE REVIEW

**Review by idamakela — CHANGES_REQUESTED** [review]
I can see how this component can be reused, especially with the props. But I would love a light-grey background for hover on the options list.

**Review by idamakela — APPROVED** [review]
Looks great!

**Comment by ell-ska** [comment]
to test: head to /playground and you should see the dropdown

**Comment by idamakela** [comment]
DEV TEST: Love the hover effect, but it seems to be stuck on hr as selected

**Comment by ell-ska** [comment]
if you look at the code it's not supposed to be functional, the function will be decided once used since we dont know what exactly it should do. its meant to be as reusable as possible. right now in development it just console logs the value you clicked on.

lets discuss the styling when you get here cause i dont really understand you vision!

**Comment by idamakela** [comment]
We spoke about it in person, and the DEV TEST IS OK!

**Pull request merged**
