### PR TITLE
[JOLINT-64] how it works section

### PR DESCRIPTION
**Pull request by ell-ska**

### CODE REVIEW

**Review by xxrobone — COMMENTED** [review]
Är Gappen rätt för How it works container? med gap  6 12 20 ?

**Review by idaakermark — APPROVED** [review]

**Comment by ell-ska** [comment]
@xxrobone looks right to me, it's the same as the design

**Comment by ell-ska** [comment]
ready for testing!

**Review by petksks — APPROVED** [review]

**Comment by DavidDyberg** [comment]
Dev test:
Really good solution with the timeline, great job! Everything looks good.
Ready for production wohoo!!

**Pull request merged**
