### PR TITLE
[FIX-25] full vh sidebar

### PR DESCRIPTION
**Pull request by idamakela**

### CODE REVIEW

**Review by ell-ska — APPROVED** [review]

**Comment by idamakela** [comment]
Ready for dev testing!

**Comment by idamakela** [comment]
I made the same mistake here, merged develop into the feature branch. I WILL FIX IT!

**Comment by idamakela** [comment]
Reverted develop merge into fix AND ready for testing!

**Comment by DavidDyberg** [comment]
Dev test:
It looks good now Ida. Ready for production! Good job!

**Comment by idamakela** [comment]
NOTES: I should not have used the -m flag on the revert command

**Pull request merged**
